networks:
  seichi:
    external: false

volumes:
  paper_a:
  paper_b:
  db-data:
  redis-data:

services:
  papera:
    build:
      context: .
      dockerfile: ./docker/paper/Dockerfile
    networks:
      - seichi
    volumes:
      - paper_a:/data
    ports:
      - "25566:25565"
      - "7091:7091"
    environment:
      - VERSION=1.18.2
      - EULA=TRUE
      - TYPE=PAPER
      - ONLINE_MODE=FALSE
      - ENABLE_JMX=true
      - JMX_PORT=7091
      - JMX_BINDING=0.0.0.0
      - JMX_HOST=localhost
      - SERVER_NUM=1
      - SERVER_ID=local-s1
      - DB_HOST=db
      - DB_PASSWORD=unchamaisgod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    stdin_open: true
  paperb:
    build:
      context: .
      dockerfile: ./docker/paper/Dockerfile
    networks:
      - seichi
    volumes:
      - paper_b:/data
    ports:
      - "25567:25565"
      - "7092:7091"
    environment:
      - VERSION=1.18.2
      - EULA=TRUE
      - TYPE=PAPER
      - ONLINE_MODE=FALSE
      - ENABLE_JMX=true
      - JMX_PORT=7091
      - JMX_BINDING=0.0.0.0
      - JMX_HOST=localhost
      - SERVER_NUM=2
      - SERVER_ID=local-s2
      - DB_HOST=db
      - DB_PASSWORD=unchamaisgod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    stdin_open: true
  bungeecord:
    image: itzg/bungeecord:java17
    ports:
      - "25565:25577"
    volumes:
      - ./docker/bungeecord/serverfiles:/config
      - ./docker/bungeecord/serverfiles/redisbungee/config.yml:/plugins/RedisBungee/config.yml
    networks:
      - seichi
    environment:
      - PLUGINS=https://github.com/ProxioDev/RedisBungee/releases/download/0.10.1/RedisBungee-Bungee-0.10.1-SNAPSHOT.jar
    depends_on:
      - papera
      - paperb
    stdin_open: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    environment:
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=unchamaisgod
    networks:
      - seichi
    ports:
      - "8080:80"
    depends_on:
      - db
  redis:
    image: "ghcr.io/giganticminecraft/bungeesemaphore-redis-dev:e57e9e7"
    networks:
      - seichi
    volumes:
      - redis-data:/data
  db:
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=unchamaisgod
      - MYSQL_DATABASE=seichiassist
    command: [
        '--wait_timeout=86400',
    ]
    networks:
      - seichi
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/config/mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"
