name: SeichiAssist
main: com.github.unchama.seichiassist.SeichiAssist
version: 0.9.34

commands:
  gacha:
      description: This is a gacha command.
      usage: /<command> <help>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  seichi:
      description: This is a seichi command.
      usage: /<command> <help>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  ef:
      description: This is a Effect toggle command.
      usage: /<command> <smart/demo>
      permission: multiseichiplugin.ef
      permission-message: You don't have <permission>
  level:
      description: This is a level command.
      usage: /<command> <help>
      permission: multiseichiplugin.level
      permission-message: You don't have <permission>
  lastquit:
      description: This is a lastquit command.
      usage: /<command> <playername>
      permission: multiseichiplugin.lastquit
      permission-message: You don't have <permission>
  rmp:
      description: This is a remove protect command.
      usage: /<command> <playername>
      permission: multiseichiplugin.rmp
      permission-message: You don't have <permission>
  stick:
      description: This is a stick command.
      usage: /<command>
      permission: multiseichiplugin.stick
      permission-message: You don't have <permission>
  shareinv:
      description: This is a share inventory command.
      usage: /<command>
      default-permission: NOT_OP
      permission-message: You don't have <permission>
  mebius:
      description: This is a mebius command.
      usage: /<command>
      default-permission: NOT_OP
      permission-message: You don't have <permission>
  achv:
      description: The command to give/deprive seichi achievements.
      usage: /<command> <GIVE/DEPRIVE> <AchievementNumber> <PlayerName/ALL/WORLD>
      permission: multiseichiplugin.achievement
  halfguard:
      description: This is a Halfblockprotect command.
      usage: /<command>
      permission: multiseichiplugin.halfguard
      permission-message: You don't have <permission>
  event:
      description: This is New Year Event command.
      usage: /<command> get
      permission: multiseichiplugin.event
      default-permission: OP
  contribute:
      description: This is a Contribute command.
      usage: /<command> <help/add/remove> <playername> <point>
      permission: multiseichiplugin.contribute
      permission-message: You don't have <permission>
  subhome:
      description: This is a SubHome command.
      usage: /<command> <help/set/name/num> <num>
      permission: multiseichiplugin.subhome
      permission-message: You don't have <permission>
  gtfever:
      description: This is a GiganticFever command.
      usage: /<command>
      permission: multiseichiplugin.gtfever
      permission-message: You don't have <permission>
  minehead:
      description: This is a MineHead command.
      usage: /<command>
      permission: multiseichiplugin.minehead
      permission-message: You don't have <permission>
