name: @name@
main: com.github.unchama.seichiassist.SeichiAssist
version: @version@

softdepend: [WorldGuard, CoreProtect]

loadbefore:
  # ワールドマイグレーション時にこれらプラグインのタスクがworldへの参照を持ちデータのGCが行われなくなる
  - Shopkeepers
  - WeatherRestrictions

default-permission-message: &denied You don't have <permission>
commands:
  gacha:
    description: Gacha operation command.
    permission: seichiassist.seichi
    permission-message: *denied
  seichihaste:
    description: Mining speed operation command.
    permission: seichiassist.seichihaste
    permission-message: *denied
  seichiassist:
    description: SeichiAssist command.
    permission: seichiassist.seichiassist
    permission-message: *denied
  openpocket:
    description: Open pocket.
    permission: seichiassist.openpocket
    permission-message: *denied
  ef:
    description: Effect operation command.
    permission: seichiassist.ef
    permission-message: *denied
    aliases:
      - effect
  lastquit:
    description: Show last logout.
    permission: seichiassist.lastquit
    permission-message: *denied
  rmp:
    description: Delete unused Regions.
    permission: seichiassist.rmp
    permission-message: *denied
  map:
    description: Show map URL.
    permission: seichiassist.map
    permission-message: *denied

  stick:
    description: Get a stick.
    permission: seichiassist.stick
    permission-message: *denied
  shareinv:
    description: Share inventory.
    permission: seichiassist.shareinv
    permission-message: *denied
  mebius:
    description: MEBIUS operation command.
    permission: seichiassist.mebius
    permission-message: *denied
  achievement:
    description: Achievement operation command.
    usage: /<command> <操作> <実績No> <スコープ指定子>
    permission: seichiassist.achievement
    permission-message: *denied
  halfguard:
    description: Toggle half block protection.
    permission: seichiassist.halfguard
    permission-message: *denied
  event:
    description: Event command.
    permission: seichiassist.event
    permission-message: *denied
  contribute:
    description: Contribution operation command.
    permission: seichiassist.contribute
    permission-message: *denied
  subhome:
    description: Subhome operation command.
    permission: seichiassist.subhome
    permission-message: *denied
  gtfever:
    description: GiganticFever start command.
    permission: seichiassist.gtfever
    permission-message: *denied
  minehead:
    description: Minehead command.
    permission: seichiassist.minehead
    permission-message: *denied
  x-transfer:
    description: Command to change the owner of a Region.
    usage: /<command> [region name] [new owner name]
    permission: seichiassist.x-transfer
    permission-message: *denied
  fly:
    description: This is a fly command.
    permission-message: *denied
    permission: buildassist.build

permissions:
  seichiassist.*:
    default: false
    children:
      - seichiassist.seichi
      - seichiassist.seichihaste
      - seichiassist.seichiassist
      - seichiassist.openpocket
      - seichiassist.ef
      - seichiassist.lastquit
      - seichiassist.rmp
      - seichiassist.map
      - seichiassist.stick
      - seichiassist.shareinv
      - seichiassist.mebius
      - seichiassist.achievenemt
      - seichiassist.halfguard
      - seichiassist.event
      - seichiassist.contribute
      - seichiassist.subhome
      - seichiassist.gtfever
      - seichiassist.minehead
      - seichiassist.x-transfer
      - buildassist.build
  seichiassist.event:
    default: op
  seichiassist.shareinv:
    default: not op
  seichiassist.mebius:
    default: not op
