name: @name@
main: com.github.unchama.seichiassist.SeichiAssist
version: @version@

api-version: 1.18

softdepend: [WorldGuard, CoreProtect, NBTAPI, Multiverse-Core, RegenWorld]

loadbefore:
  # ワールドマイグレーション時にこれらプラグインのタスクがworldへの参照を持ちデータのGCが行われなくなる
  - Shopkeepers
  - WeatherRestrictions

default-permission-message: &denied You don't have permission. (<permission>) Please report this if you think this is an error.
commands:
  gacha:
    description: Gacha operation command.
    permission: seichiassist.seichi
    permission-message: *denied
  vote:
    description: Vote operation command.
    permission: seichiassist.seichi
    permission-message: *denied
  donation:
    description: Donation operation command.
    permission: seichiassist.seichi
    permission-message: *denied
  seichiassist:
    description: SeichiAssist command.
    permission: seichiassist.seichiassist
    permission-message: *denied
  openpocket:
    description: Open pocket.
    permission: seichiassist.openpocket
    permission-message: *denied
  ef:
    description: Effect operation command.
    permission: seichiassist.ef
    permission-message: *denied
    aliases:
      - effect
  lastquit:
    description: Show last logout.
    permission: seichiassist.lastquit
    permission-message: *denied
  rmp:
    description: Delete unused Regions.
    permission: seichiassist.rmp
    permission-message: *denied
  map:
    description: Show map URL.
    usage: /<command>
    permission: seichiassist.map
    permission-message: *denied
  stick:
    description: Get a stick.
    usage: /<command>
    permission: seichiassist.stick
    permission-message: *denied
  shareinv:
    description: Share inventory.
    permission: seichiassist.shareinv
    permission-message: *denied
  mebius:
    description: MEBIUS operation command.
    permission: seichiassist.mebius
    permission-message: *denied
  achievement:
    description: Achievement operation command.
    usage: /<command> <操作> <実績No> <スコープ指定子>
    permission: seichiassist.achievement
    permission-message: *denied
  halfguard:
    description: Toggle half block protection.
    permission: seichiassist.halfguard
    permission-message: *denied
  event:
    description: Event command.
    permission: seichiassist.event
    permission-message: *denied
  home:
    description: Home operation command.
    permission: seichiassist.home
    permission-message: *denied
  sethome:
    description: Set HomePoint command.
    permission: seichiassist.home
    permission-message: *denied
  gtfever:
    description: GiganticFever start command.
    permission: seichiassist.gtfever
    permission-message: *denied
  minehead:
    description: Minehead command.
    permission: seichiassist.minehead
    permission-message: *denied
  x-transfer:
    description: Command to change the owner of a Region.
    usage: /<command> [region name] [new owner name]
    permission: seichiassist.x-transfer
    permission-message: *denied
  fly:
    description: This is a fly command.
    usage: /<command> <操作> (詳細については/fly helpを参照してください)
    permission-message: *denied
    permission: seichiassist.fly
  stickmenu:
    description: 棒メニューを開く
    usage: /<command>
    permission: seichiassist.stickmenu
    permission-message: *denied
    aliases:
      - sm
  fd:
    description: 四次元ポケットを開く
    usage: /<command>
    permission: seichiassist.fd
    permission-message: *denied
  present:
    description: send a gift
    usage: /present <操作> (詳細については/present helpを参照してください)
    permission-message: *denied
  hat:
    description: set item in hand to head
    usage: /<command>
    permission-message: *denied
    permission: seichiassist.hat
  ec:
    description: エンダーチェストを開く
    usage: /<command>
    permission: seichiassist.ec
    permission-message: *denied
  minestack:
    description: Toggle whether minestack collects applicable item automatically
    usage: /minestack <on | off | open | store-all>
    aliases:
      - ms
    permission-message: *denied
    permission: seichiassist.minestack
permissions:
  seichiassist.*:
    default: false
    children:
      - seichiassist.seichi
      - seichiassist.seichiassist
      - seichiassist.openpocket
      - seichiassist.ef
      - seichiassist.lastquit
      - seichiassist.rmp
      - seichiassist.map
      - seichiassist.stick
      - seichiassist.shareinv
      - seichiassist.mebius
      - seichiassist.achievenemt
      - seichiassist.halfguard
      - seichiassist.event
      - seichiassist.home
      - seichiassist.gtfever
      - seichiassist.minehead
      - seichiassist.x-transfer
      - seichiassist.fly
      - seichiassist.stickmenu
      - seichiassist.fd
      - seichiassist.present.*
      - seichiassist.hat
  seichiassist.event:
    default: op
  seichiassist.shareinv:
    default: true
  seichiassist.mebius:
    default: true
  seichiassist.minestack:
    default: true
  seichiassist.present.grant:
    default: op
    description: "'/present grant' の使用許可を与える。"
  seichiassist.present.revoke:
    default: op
    description: "'/present revoke' の使用許可を与える。"
  seichiassist.present.define:
    default: op
    description: "'/present define' の使用許可を与える。"
  seichiassist.present.delete:
    default: op
    description: "'/present delete' の使用許可を与える。"
  seichiassist.present.*:
    default: op
    children:
      - seichiassist.present.grant
      - seichiassist.present.revoke
      - seichiassist.present.define
      - seichiassist.present.delete
