blank_issues_enabled: true
contact_links:
  - name: 公式Discordグループ内 "#不具合報告"
    about: GitHubに慣れていない方は公式Discordグループからでも不具合を報告できます。
    url: https://discord.gg/GcJtgsCj3W
  - name: 不具合フォーム
    about: 悪用やセキュリティの脆弱性に関わる不具合は、こちらのフォームから報告してください。
    url: https://portal.seichi.click/forms/01a04c05-2cd2-74b0-bf0c-eab63b3f2213
