name: Auto attach label to PR
on:
  pull_request:
    types: [opened]

jobs:
  auto-attach-label:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Attach label to PR
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          if [[ "$BRANCH_NAME" == "feat"* ]]; then
            LABEL="feature"
          elif [[ "$BRANCH_NAME" == "fix"* ]]; then
            LABEL="bug"
          elif [[ "$BRANCH_NAME" == "development"* ]]; then
            LABEL="development"
          elif [[ "$BRANCH_NAME" == "refactor"* ]]; then
            LABEL="refactoring"
          elif [[ "$BRANCH_NAME" == "ci/"* ]]; then
            LABEL="Build / CI"
          else
            echo "No matching label found for branch name: $BRANCH_NAME"
            exit 0
          fi
          
          gh pr edit "$PR_NUMBER" --add-label "$LABEL"
