name: Check Renovate Config

on:
  pull_request:
    paths:
      - ./github/workflows/check-renovate-config.yaml
      - .renovate.json

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: "0"

      - name: Install npm
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24"

      - name: Check Renovate configuration
        run: npx --yes --package renovate -- renovate-config-validator --strict
