name: Check Renovate Config

on:
  pull_request:
    paths:
      - ./github/workflows/check-renovate-config.yaml
      - .renovate.json

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: "0"

      - name: Install npm
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"

      - name: Check Renovate configuration
        run: npx --yes --package renovate -- renovate-config-validator --strict
