name: Create release

on:
  push:
    branches:
      - master

jobs:
  create_seichiassist_release:
    runs-on: ubuntu-24.04
    container: ghcr.io/giganticminecraft/seichiassist-builder-v2:1df7cf5
    steps:
      - uses: actions/checkout@master
        with:
          # これがないとchunk_searchで引っかかってリリースのjarアップロードに失敗する
          submodules: "recursive"

      - name: Prepare build environment for seichiassist
        uses: ./.github/actions/prepare-build-environment-for-seichiassist

      - name: build artifacts
        run: mkdir -p target/build && sbt assembly

      - name: Get current version
        id: get_current_version
        run: |
          get_defined_versions () {
            grep -o -P "(?<=ThisBuild / version := \")\d+(?=\")" build.sbt
          }
          
          if [ ! $(get_defined_versions | wc -l) = "1" ]; then
            echo "エラー：build.sbt でのバージョン指定が一意でありません。"
            exit 1
          fi

          echo "current_version=$(get_defined_versions)" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: target/build/SeichiAssist.jar
          # seichi_infra に定義されている SeichiAssist のリリース用ワークフローは、
          # target_commitish が master のときに正式リリースだと認識する。
          # デフォルト値は GitHub で設定されているデフォルトブランチになる。
          target_commitish: master
          generate_release_notes: true
          tag_name: "v${{ steps.get_current_version.outputs.current_version }}"
          draft: false
          prerelease: false
          # make_latest は String を期待している
          make_latest: "true"
