name: Docker build check

on:
  workflow_call:

jobs:
  docker_build_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build Paper image
        run: |
          mkdir -p target/build
          docker build --tag seichiassist-paper:ci --file docker/paper/Dockerfile .

      - name: Build MariaDB image
        run: docker build --tag seichiassist-mariadb:ci --file docker/mariadb/Dockerfile .
