name: Incremental build and test

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: adoptopenjdk:8u282-b08-jdk-openj9-0.24.0
    steps:
      - name: Check git version
        run: git --version
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Cache build dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-build-dependencies
          cache-version: v-minus-1
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2
            ~/.cache/coursier/v1
            ~/.sbt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Test and build artifact
        run: ./sbt assembly
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SeichiAssist-build
          path: target/build/**.jar
