name: Incremental build and test

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: ghcr.io/giganticminecraft/seichiassist-builder:2684219
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache build dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-build-dependencies
          cache-version: v-minus-1
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2
            ~/.cache/coursier/v1
            ~/.sbt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Test and build artifact
        run: ./sbt assembly

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SeichiAssist-build
          path: target/build/**.jar

  deploy-artifact:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: SeichiAssist-build
        id: download
      - name: Inspect artifact
        run: du -h --max-depth=2 ${{ steps.download.outputs.download-path }}
      - name: Deploy to staging environment
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.STAGING_KEY }}
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          source: ${{ steps.download.outputs.download-path }}/**.jar
          username: ${{ secrets.STAGING_USERNAME }}
          remote_dir: ${{ secrets.STAGING_REMOTE_DIR }}
