name: Lint SQL files
on:
  pull_request:
    paths:
      - src/main/resources/db/migration/**/*.sql
      - .github/workflows/lint_sql.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yu-iskw/action-sqlfluff@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_command: lint
          dialect: mysql
          fail_on_error: true
          config: ./.sqlfluff
          paths: ./src/main/resources/db/migration
